'use client';

import { useEffect, useState } from 'react';
import { ExternalLink, TrendingUp } from 'lucide-react';

interface Insight {
  insight_id: string;
  question: string;
  answer_text: string;
  confidence_score: number;
  spec_id: string;
  created_at: string;
  trace_url: string | null;
}

function ConfidencePill({ score }: { score: number }) {
  const pct = Math.round(score * 100);
  const color = pct >= 80 ? '#16a34a' : pct >= 60 ? '#d97706' : '#dc2626';
  const bg    = pct >= 80 ? '#f0fdf4' : pct >= 60 ? '#fffbeb' : '#fef2f2';
  return (
    <span className="rounded-full px-2 py-0.5 text-[11px] font-semibold" style={{ color, backgroundColor: bg }}>
      {pct}%
    </span>
  );
}

export default function InsightsPage() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/insights')
      .then((r) => r.json())
      .then((d) => setInsights(Array.isArray(d) ? d : []))
      .catch(() => setInsights([]))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="flex h-full flex-col">
      <div className="border-b px-8 py-5" style={{ borderColor: '#e5dfd6' }}>
        <h1 className="text-lg font-semibold" style={{ color: '#1c1814' }}>Insights</h1>
        <p className="mt-0.5 text-sm" style={{ color: '#9c9088' }}>
          PM-ready findings generated by the Analytics Agent after each spec run.
        </p>
      </div>

      <div className="flex-1 overflow-y-auto px-8 py-8">
        {loading && (
          <div className="flex h-40 items-center justify-center">
            <p className="text-sm" style={{ color: '#9c9088' }}>Loading…</p>
          </div>
        )}

        {!loading && insights.length === 0 && (
          <div className="flex h-full flex-col items-center justify-center text-center">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl mb-5" style={{ backgroundColor: '#f0ece6' }}>
              <TrendingUp className="h-7 w-7" style={{ color: '#9c9088' }} />
            </div>
            <h2 className="text-base font-semibold" style={{ color: '#1c1814' }}>No insights yet</h2>
            <p className="mt-1.5 max-w-xs text-sm" style={{ color: '#9c9088' }}>
              Insights appear here after a spec has been fully executed by the pipeline.
            </p>
          </div>
        )}

        {!loading && insights.length > 0 && (
          <div className="max-w-2xl space-y-4">
            {insights.map((ins) => (
              <div key={ins.insight_id} className="rounded-2xl border p-5 space-y-3"
                style={{ borderColor: '#e5dfd6', backgroundColor: '#ffffff' }}>
                <div className="flex items-start justify-between gap-3">
                  <h3 className="text-sm font-semibold leading-snug" style={{ color: '#1c1814' }}>{ins.question}</h3>
                  <ConfidencePill score={ins.confidence_score} />
                </div>
                <p className="text-sm leading-relaxed" style={{ color: '#4a4540' }}>{ins.answer_text}</p>
                <div className="flex items-center justify-between pt-1">
                  <span className="text-xs" style={{ color: '#c0b8b0' }}>{ins.spec_id} · {ins.created_at}</span>
                  {ins.trace_url && (
                    <a href={ins.trace_url} target="_blank" rel="noopener noreferrer"
                      className="flex items-center gap-1 text-xs font-medium hover:opacity-70" style={{ color: '#2563eb' }}>
                      View trace <ExternalLink className="h-3 w-3" />
                    </a>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
